#!/usr/bin/env  bash

FS=':%:' # field separator
KVS=':!:' # key-value separator

__bbdb_mydbfile="undef"
bbdb_open ()  {
    local db_file="$1"
    [[ ! -f "$db_file" ]] && touch "$db_file"
    __bbdb_mydbfile="$db_file"
}

##
bbdb_construct_entry () {
    # keyvalue pairs key=value key=value
    for kv in "$@" ; do echo "$kv" ; done | awk -v kvs="$KVS" -v fs="$FS" 'BEGIN{ORS=fs}{ sub("=",kvs) ; print }' | awk -v fs="$FS" '{ sub( fs "$", "") ; print }'
}

bbdb_commit_entry () {
    [[ "$__bbdb_mydbfile" == "undef" ]] && echo 'no defined db' && exit 2
    #####
    local entry="$1"
    echo "$entry" >> "$__bbdb_mydbfile"
}

bbdb_entry_to_readable_lines () {
    local entry="$1"
    echo "$entry" | awk -v fs="$FS" -v kv="$KVS" '{ gsub(fs,"\n") ; gsub(kv,"=") ; print }'
}

bbdb_split_entry_to_lines () {
    local entry="$1"
    echo "$entry" | awk -v fs="$FS" '{ gsub(fs,"\n") ; print }'
}

bbdb_query () {
    # key=value key=value .. ==> list of matching entries
    [[ "$__bbdb_mydbfile" == "undef" ]] && echo 'no defined db' && exit 2
    #####

    local db="$(cat "$__bbdb_mydbfile")"
    for querykv in "$@" ; do
        db="$(echo "$db" | awk -v querykv="$querykv" -v kvs="$KVS" -v fs="$FS" 'BEGIN{ sub("=",kvs,querykv) } {if ( $0 ~ "(^|" fs ")" querykv "($|" fs ")" ) { print }  }')"
    done
    echo "$db"
}

bbdb_extract_value_from_entry () {
    # entry keyname ==> value
    local entry="$1"
    local key="$2"

    echo "$entry" | awk -F "$FS" -v kvs="$KVS" -v keyname="$key" '{ for ( i = 1 ; i <= NF ; ++i ) { if ( $i ~ "^" keyname kvs ) { sub( "^" keyname kvs , "" , $i ) ; print $i ; break } } }'
}

bbdb_delete_entry () {
    [[ "$__bbdb_mydbfile" == "undef" ]] && echo 'no defined db' && exit 2
    #####
    local entry="$1"

    local tmpfile=/tmp/$RANDOM$RANDOM$RANDOM
    cp "$__bbdb_mydbfile" $tmpfile
    cat $tmpfile | awk -v entry="$entry" '{ if ( $0 != entry ) { print } }' > "$__bbdb_mydbfile"
    rm -f "$tmpfile"
}

bbdb_modify_entry_and_commit () {
    # entry key newvalue    ==> new entry 
    # also, it will commit the change,
    # IT WILL NOT COMMIT THE CHANGES
    [[ "$__bbdb_mydbfile" == "undef" ]] && echo 'no defined db' && exit 2
    #####
    local entry="$1"
    local keyname="$2"
    local newvalue="$3"

    bbdb_delete_entry  "$entry"
    local newentry="$(bbdb_modify_entry "$entry" "$keyname" "$newvalue")"
    bbdb_commit_entry  "$newentry"
}

bbdb_modify_entry () {
    # entry key newvalue    ==> new entry 
    # also, it will commit the change,
    # IT WILL NOT COMMIT THE CHANGES
    local entry="$1"
    local keyname="$2"
    local newvalue="$3"

    echo "$entry" | awk -F "$FS" -v kvs="$KVS" -v keyname="$keyname" -v newvalue="$newvalue" 'BEGIN{OFS=FS ; exist=0}{ for ( i = 1 ; i <= NF ; ++i ) { if ( $i ~ "^" keyname kvs  ) {exist=1 ;  $i = keyname kvs  newvalue } } }  END{ if ( exist == 0 ) { $0 = $0 FS keyname kvs newvalue } ; print $0 }'
}

bbdb_dump () {
    [[ "$__bbdb_mydbfile" == "undef" ]] && echo 'no defined db' && exit 2
    #####
    cat "$__bbdb_mydbfile"
}
